baseURL = 'https://share-meganii-com.pages.dev/'
languageCode = 'ja-jp'
title = 'My recommend items'

theme = "tailwind"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "tango"
    tabWidth = 4